### ISSUE TITLE
User can view user Detail

### ISSUE THREAD

**Issue by sulha199** [supertokens/dashboard#39]
https://app.zeplin.io/project/5aaa0de98d835c7b25637f2e/screen/6290ccd63d284c2b8ef59a46

**Comment by rishabhpoddar** [comment]
## Feedback (28th Oct 2022)

- [ ] Change password modal should have label as "New password" and "Confirm new password"
- [ ] Change password modal should not do password verification on the frontend, it should use the user defined (or default) password validator on the backend.
- [ ] Quotes in "?" hover in user details (next to name) should be normal ones.
- [ ] Add a copy button next to session handle
- [ ] In delete user popup, ask the user to type the email / phone number to confirm
- [ ] First name and last name hover, you should change the hover text to say that it's fetched from the user metadate with this key
- [ ] Allow first / last name to be editable without the user manually changing the metadata on the dashboard.
- [ ] In the user details page, we need to show which recipe the user used to sign in
- [ ] In session list, don't bother with pagination of sessions
- [ ] In backend API for session  list, we can just call all APIs for getting session info in parallel
- [ ] In the users info API, you need to check all recipes - if input recipe ID is emailpassword, then you should check for emailpassword and thirdpartyemailpassword recipes
- [ ] The API spec for get session list should change to use sessionData and accessTokenPayload instead of userDataInDatabase or userDataInJWT
- [ ]  Change API definition in backend to return the typed response instead of boolean. This ensures that we follow the API spec over time. In these types, don't reuse types from within the SDKs, but explicitly define the types.

**Comment by nkshah2** [comment]
- [ ] Add copy option for email
