### ISSUE TITLE
Add email password sign in to dashboard

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/dashboard#55]
## New core APIs:
- create user with email password and name
- verify email password
- update password for user
- get list of users
- get JWT public signing key
- delete user
- does use exist

## New APIs in backend SDK
- Sign in
- Sign out

## Auth method change in backend SDK
Verify the JWT and then query the core to check if the user exists or not.

## Frontend change
- Build sign in screen
- Building sign up screen which just shows curl commands to add a new user in the core with the right core URL.
- Send JWT as a header
- In sign up form, we should explain where to get the connectionURI and API key for the core.

**Comment by rishabhpoddar** [comment]
## MVP version
- Sign up via curl command to the core. Curl command will take email and password of new user.
- Sign in via created email and password.

## V2:
- Create only the initial user for the dashboard via Curl
- New users will be allowed to be created via the dashboard and emails will be sent to them. Those users can then reset their passwords on the link click.

## V3:
- Multi tenancy with supertokens allowing different forms of login.

**Comment by nkshah2** [comment]
# Work in progress

## General flow

### Frontend -> Backend

- Frontend receives a JWT that is stored in local storage and sent as a Bearer authorization token in all API calls
- The frontend should display an appropriate error to the user if their credentials have been suspended (explained later)

### Backend -> Core

- Backend calls core APIs during sign in to create a JWT to be sent to the frontend
- For every API that needs auth the backend calls a verify API exposed by the Core to verify that the JWT is valid and that the user is allowed to access the dashboard

### Core

- Separate JWT signing key for the dashboard (stored in the same table as the other)
- Dashboard users are maintained in different tables and are completely independent of normal users
- The same API key is used to create and manage dashboard users and for normal core operations

## Summary of changes

### Backend SDK

#### 1. `/api/signin` POST

Used to sign the user in, this API should not perform any validation on the email/password

Request:

```ts
email: string,
password: string,
```

Response:

```ts
{status: "OK", token: string} | {status: "INVALID_CREDENTIALS_ERROR"} | {status: "USER_SUSPENDED_ERROR"}
```

#### Changes to all APIs that need auth

Request Headers:

```ts
{Authorization: "Bearer <token>"}
```

The absence of the header should be treated as unauthorised. Every API call should call the Core to verify the JWT, if the JWT is invalid or the user has been suspended the API should return unauthorised.

### Core

#### Table Schema

| id | email | is_suspended | time_joined | password_hash |
| - | - | - | - | - |
| uid (primary) | string (unique) | bool | number | string |

#### General Notes

- When creating users check if the feature flag for dashboard is enabled, If yes continue. If no check if the total number of users in the table (suspended or otherwise) is greater than or equal to 2. If more than 2 then the operation should not be allowed

- During sign in if the feature flag is not enabled, check if the user is suspended and block the operation if they are.

- All operations first call a common function. This function will check if the feature flag is enabled, if it isnt then mark all users other than the oldest 2 users in the table (based on time_joined) as suspended. If it is enabled then mark users in the table as not suspended

**Comment by nkshah2** [comment]
@jscyo @AreebKhan619 review when you can ^

**Comment by jscyo** [comment]
The dashbaord_emailpassword_users schema will not have the `is_suspended` field. We are removing this field because it is an extra entry in the db which will have to be managed whenever updates or deletes are done. Instead, we will find if this information is based on time_joined and the number of users.

**Comment by jscyo** [comment]
## New Changes

- Instead of creating a JWT, creating sessions for the users would be simpler. We will have a separate `dashboard_user_sessions` table where we map the user's userId to their session with the primary key being(userId, sessionId) with the time_created of the session.
- Additionally, there should be an expiry time for the sessions. So if the time_created for the session is more than **30** days the session should be removed

**Comment by nkshah2** [comment]
@jscyo @AreebKhan619 Ive updated the spec, summary of changes:

## On the backend SDKs:
- `/user/signin POST` API response, `token` has been renamed to `sessionId`


## Core

- `/recipe/dashboard/user PUT`, the API responds with status code 402 if the user limit has been reached (@AreebKhan619  this may need special handling in the backend SDK)
- `/recipe/dashboard/verify POST`, `token` renamed to `sessionId` and `INVALID_JWT` has been renamed to `INVALID_SESSION`. Added `USER_SUSPENDED_ERROR` to possible return status types.
- `/recipe/dashboard/signin POST`: `jwt` renamed to `sessionId`

**Comment by jscyo** [comment]
Errors which require message for additional context

`USER_SUSPENDED_ERROR`
`WEAK_PASSWORD_ERROR`
`USER_LIMIT_REACHED_ERROR`

**Comment by nkshah2** [comment]
/user PUT API should clear all current sessions of the user if the email or password or both have been modified

@jscyo
